version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install -r requirement.txt
      - pip3 install pytest
      - pip3 install flake8
  pre_build:
    commands:
      - flake8
      - pytest -s -v
